// <auto-generated />
using System;
using Infrastructure.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MediaNirvanaDbContext))]
    [Migration("20251216093900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.MediaItemCreator", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId", "CreatorId");

                    b.HasIndex("CreatorId");

                    b.ToTable("MediaItemCreators");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.MediaItemGenre", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaItemGenres");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.UserInteractionTag", b =>
                {
                    b.Property<Guid>("UserInteractionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserInteractionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("UserInteractionTags");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.UserLabelLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserLabelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserLabelId", "TargetType");

                    b.ToTable("UserLabelLinks");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.MediaInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MediaInstances");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationDescription")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMediaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetMediaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetMediaId");

                    b.HasIndex("SourceMediaId", "TargetMediaId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PersonalRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaInstanceId");

                    b.HasIndex("UserId", "MediaInstanceId");

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type");

                    b.ToTable("UserLabels");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.MediaItemCreator", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.Creator", "Creator")
                        .WithMany("MediaItemCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.MediaItem", "MediaItem")
                        .WithMany("MediaItemCreators")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.MediaItemGenre", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.Genre", "Genre")
                        .WithMany("MediaItemGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.MediaItem", "MediaItem")
                        .WithMany("MediaItemGenres")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.UserInteractionTag", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.Tag", "Tag")
                        .WithMany("UserInteractionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserInteraction", "UserInteraction")
                        .WithMany("Tags")
                        .HasForeignKey("UserInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("UserInteraction");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.ConnectingEntity.UserLabelLink", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserLabel", "UserLabel")
                        .WithMany("Links")
                        .HasForeignKey("UserLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLabel");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.MediaInstance", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.MediaItem", "MediaItem")
                        .WithMany("Instances")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.Relationship", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.MediaItem", "SourceMedia")
                        .WithMany("RelationshipsSource")
                        .HasForeignKey("SourceMediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.MediaItem", "TargetMedia")
                        .WithMany("RelationshipsTarget")
                        .HasForeignKey("TargetMediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceMedia");

                    b.Navigation("TargetMedia");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserInteraction", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.MediaInstance", "MediaInstance")
                        .WithMany("Interactions")
                        .HasForeignKey("MediaInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.User", "User")
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserLabel", b =>
                {
                    b.HasOne("Infrastructure.EF.Entity.IndependentEntity.User", "User")
                        .WithMany("Labels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.Creator", b =>
                {
                    b.Navigation("MediaItemCreators");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.MediaInstance", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserInteraction", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.DependentEntity.UserLabel", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.Genre", b =>
                {
                    b.Navigation("MediaItemGenres");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.MediaItem", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("MediaItemCreators");

                    b.Navigation("MediaItemGenres");

                    b.Navigation("RelationshipsSource");

                    b.Navigation("RelationshipsTarget");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.Tag", b =>
                {
                    b.Navigation("UserInteractionTags");
                });

            modelBuilder.Entity("Infrastructure.EF.Entity.IndependentEntity.User", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
